apiVersion: v1
kind: Pod
metadata:
    name: demo-pod
spec:
    containers:
    -   name: demo-nginx
        image: nginx
    -   name: demo-centos
        image: centos
        command: ["/bin/sh", "-c", "while : ; do curl http://localhost:80/; sleep 25; done"]
